/**
 * Daily citations for the Habitus application.
 * Each citation will be shown as a tooltip on the icon next to the Habitus title.
 * Citations rotate daily based on the day of the year (1-366).
 * There are 366 citations, one for each day of the year (including leap years).
 */

/**
 * Array of 366 citations.
 * Each citation should be a string with the quote text.
 * Citations are used sequentially by day number (day 1 = citation[0], day 2 = citation[1], etc.)
 */
export const citations: string[] = [
  "Winners disciplined. - Thomas Peterffy",
  "Where your habits go, your life follows. - Craig Groeschel",
  "Simple daily disciplines equal success. - Jim Rohn",
  "One of the healthiest habits to learn: Being grateful for the little things. - Yung Pueblo",
  "When we make a consistent practice of choosing the courageous response, courage becomes a habit. - Unknown",
  "We're not aiming for perfection here, only consistency. - BJ Fogg",
  "Practice isn't the thing you do once you're good. It's the thing you do that makes you good. - Malcolm Gladwell",
  "The great enemy of good habits is not a bad day, but giving up after it. - Unknown",
  "Don't expect to be motivated every day to get out there and make things happen. You won't be. Don't count on motivation; count on discipline. - Jocko Willink",
  "Natural success via habit. - Kobe Bryant",
  "If you plant the wrong habits, you will harvest the wrong future. - Craig Groeschel",
  "It's not what we do once in a while that shapes our lives. It's what we do consistently. - Tony Robbins",
  "A habit must be established before it can be improved. - James Clear",
  "Quality habit, not act. - Aristotle",
  "Bad habits like comfy beds. - Unknown",
  "Persistence is the twin sister of excellence; one is a matter of quality, the other a matter of habit. - Marabel Morgan",
  "Routine organize room. - Jordan Peterson",
  "Change your habits, and your habits will change your confidence. - Unknown",
  "Right acts habit virtue. - Aristotle",
  "Cultivate self-discipline. - Unknown",
  "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
  "Sow thought, reap destiny. - Ralph Waldo Emerson",
  "Habits are cobwebs at first, cables at last. - Spanish Proverb",
  "Don't make a habit out of choosing what feels good over what's actually good for you. - Eric Thomas",
  "Habit refines virtue. - Aristotle",
  "The second half of a man's life is made up of nothing but the habits he has acquired during the first half. - Fyodor Dostoevsky",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
  "Habits, once formed, control your life far more than decisions made in moments of passion. - Bob Goff",
  "Courage habit via consistent choice. - Unknown",
  "Habit excellence who. - Kobe Bryant",
  "Design your environment to make your habit inevitable. - Unknown",
  "Disciplines daily succeed. - Jim Rohn",
  "Consistency is contrary to nature, contrary to life. The only completely consistent people are the dead. - Aldous Huxley",
  "The most powerful habit: Use the first hour to build or produce value. - Dan Koe",
  "Great works are performed not by strength, but perseverance. - Samuel Johnson",
  "Character is simply habit long continued. - Plutarch",
  "Build good habits and consistency will do the rest. - Anthony Pompliano",
  "Success doesn't come from consistency. It comes from experimenting. - Unknown",
  "Nothing is more powerful than habit, except the will to change it. - Unknown",
  "Distracted habit rid. - John D. Rockefeller",
  "Habit stronger nothing. - Ovid",
  "The easier a behavior is to do, the more likely it becomes habit. - BJ Fogg",
  "Good habits, once established, are just as hard to break as bad ones. - Anonymous",
  "Your beliefs become your thoughts, your thoughts become your words, your words become your actions, your actions become your habits, your habits become your values, your values become your destiny. - Mahatma Gandhi",
  "Repeat until automatic. - Norman Vincent Peale",
  "Champions do daily what others do occasionally. - Michael Jordan",
  "Every action you take is a vote for the type of person you wish to become. - James Clear",
  "Self-discipline is an act of cultivation. - Unknown",
  "Over time, your habits become your home. Make sure it's a place you want to live in. - Unknown",
  "A single bad habit can undo years of good disciplines. - Anonymous",
  "Your character is your accumulation of your thoughts, habits and priorities. - Nick Saban",
  "Easy behavior habits. - BJ Fogg",
  "Make it a point to do something every day that you don't want to do. - Mark Twain",
  "Unlearning past habits that no longer serve you is self-care. - Chris Ruden",
  "The difference between amateur and professional is in their habits. - Steven Pressfield",
  "Act right to be excellent. - Aristotle",
  "The real reason habits matter is learning new habits changes your life. - Mel Robbins",
  "The greatest threat to success is not failure but boredom. - James Clear",
  "The undisciplined are slaves to their moods, appetites, and passions. - Stephen R. Covey",
  "The holy grail of habit change is not a single 1 percent improvement, but a thousand of them. - James Clear",
  "Habit is a verb. - James Clear",
  "Break tasks small to start. - Mark Twain",
  "Drop by drop the water pot is filled. - Dhammapada",
  "Do what needs to be done, even when you don't feel like doing it. - Mel Robbins",
  "Persistence conquers all. - Benjamin Franklin",
  "Uproot bad, cultivate good daily. - James Clear",
  "Analyze your schedule, kill your empty habits, burn out the bullshit, and see what's left. - David Goggins",
  "We are our best selves when we have the courage to leave behind what we no longer need. - Marie Forleo",
  "Create a personal scoring system for your habits. Award yourself points for consistency. - Unknown",
  "We first make our habits, and then our habits make our lives. - John C. Maxwell",
  "Quality is not an act; it is a habit. - Aristotle",
  "Good habits are realized dreams, bad habits are slow-motion nightmares. - Unknown",
  "Success is nothing more than a few simple disciplines, practiced every day. - Jim Rohn",
  "Habits change into character. - Ovid",
  "Do despite feelings. - Mel Robbins",
  "Self-control is strength. Right thought is mastery. Calmness is power. - James Allen",
  "Tools shape us back. - Marshall McLuhan",
  "We are what we repeatedly do. Excellence is not an act, but a habit. - Aristotle",
  "Habits are the daily decisions that define who you are becoming. - Unknown",
  "Learned that champions aren't just born; champions can be made when they embrace and commit to life‑changing positive habits. - Lewis Howes",
  "Success is something you attract by the person you become. - Jim Rohn",
  "Excellence is not a destination; it is a continuous journey that never ends, built on habit. - Brian Tracy",
  "1% thousand times. - James Clear",
  "Discipline is choosing between what you want now and what you want most. - Abraham Lincoln",
  "Your outcomes are a lagging measure of your habits. - James Clear",
  "Make it obvious. Make it attractive. Make it easy. Make it satisfying. - James Clear",
  "Failure is a few errors in judgment, repeated every day. - Jim Rohn",
  "Every act of self-control is a rehearsal for the habits you wish to own. - Unknown",
  "If you want to cultivate a habit, do it without any reservation, till it is firmly established. - Mahatma Gandhi",
  "Quit learn habit. - Vince Lombardi",
  "Small daily disciplines stack into massive results. - John C. Maxwell",
  "Successful people are simply those with successful habits. - Brian Tracy",
  "The secret of your success is found in your daily routine. - John C. Maxwell",
  "The ultimate form of intrinsic motivation is when a habit becomes part of your identity. - James Clear",
  "Make good choices a habit, not a coincidence. - Unknown",
  "Habit formation is the art of becoming someone new. - James Clear",
  "It is easier to prevent bad habits than to break them. - Benjamin Franklin",
  "Once you have established a ritual of practice, you won't need to think about motivation. - Cal Newport",
  "Start small tasks. - Mark Twain",
  "The power of habit can transform your life beyond recognition. - Sean Covey",
  "Habit quality acts. - Aristotle",
  "Consistency adaptable theory. - James Clear",
  "Drop a good habit into your day and it will quietly redesign your future. - Unknown",
  "Discipline cultivate act. - Unknown",
  "To change a habit, make a conscious decision, then act out the new behavior. - Maxwell Maltz",
  "Beds of habit: cozy entry, tough exit. - Denis Waitley",
  "Your habits are the silent architects of your life. - Colby Kultgen",
  "The fastest path to better choices is thinking about your ideal life before decisions. - Dan Koe",
  "Game your pain away. - Will Moore",
  "The first mistake is never the one that ruins you. It is the spiral of repeated mistakes that follows. - James Clear",
  "The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and starting on the first one. - Mark Twain",
  "Success is built on the foundation of the things you do when no one is watching. - H. Jackson Brown Jr.",
  "You are what you do, not what you say you'll do. - Carl Jung",
  "If you want to change your world, change your habits. - Norman Vincent Peale",
  "We shape our tools and then our tools shape us. - Marshall McLuhan",
  "Daily small disciplines stack big. - Unknown",
  "Habits are the compound interest of improvement. - James Clear",
  "Score habits, reward consistency. - Unknown",
  "Good habits, once established, are just as hard to break as bad habits. - Robert Puller",
  "Habits turn time into either a friend or an enemy; you get to choose which. - Unknown",
  "Discipline separates winners. - Thomas Peterffy",
  "Overcome habit with habit. - Desiderius Erasmus",
  "Good feels not habit. - Eric Thomas",
  "When excellence becomes a habit, success follows naturally. - Kobe Bryant",
  "Without good habits, there is no such thing as success. - Eric Thomas",
  "Chains of habit are forged one small link at a time. - Unknown",
  "Gym step forward daily. - Unknown",
  "Amateurs have a goal. Professionals have a process. - Shane Parrish",
  "Habits become character. - Ovid",
  "Discipline is built one small act of courage repeated until it becomes habit. - Mel Robbins",
  "Conquer by persistence. - Benjamin Franklin",
  "The secret to getting results that last is to never stop making improvements. - James Clear",
  "Small, smart choices plus consistency plus time equals radical difference. - Darren Hardy",
  "Repeat get you. - James Clear",
  "Our faith comes in moments; our vice is habitual. - Ralph Waldo Emerson",
  "Consistency is what transforms average into excellence. - Anonymous",
  "Motivation gets you going, but discipline keeps you growing. - John C. Maxwell",
  "Once you learn to quit, it becomes a habit. - Vince Lombardi",
  "Good habits make time your ally. Bad habits make time your enemy. - James Clear",
  "Habits are the daily votes you cast for the story you're telling with your life. - Jeff Goins",
  "The secret to getting ahead is getting started. - Mark Twain",
  "Prevent before you break. - Benjamin Franklin",
  "Small habits are louder than big plans. - Greg McKeown",
  "Overthinker habitual break. - Nick Trenton",
  "Correct your mistakes before they become your habits. - James Clear",
  "Discipline is remembering what you want. - David Campbell",
  "All men must suffer one of two pains: the pain of discipline or the pain of regret. - Jim Rohn",
  "Habit is the flywheel of excellence. - Aristotle",
  "Thousand 1% improvements win. - James Clear",
  "Refine by habit. - Aristotle",
  "Our character is basically a composite of our habits. - Stephen R. Covey",
  "Little becomes lot. - Tanzanian Proverb",
  "Grateful little habit. - Yung Pueblo",
  "The best way to get started is to quit talking and begin doing. - Walt Disney",
  "Consistency beats intensity every time. - Bruce Lee",
  "Every habit is a teacher; the question is whether it is teaching you what you want to learn. - Unknown",
  "Snail's perseverance wins. - Charles Spurgeon",
  "Good habits are worth being fanatical about. - John Irving",
  "Progress is not achieved by luck, but by working on yourself daily. - Epictetus",
  "Many of us have become habitual overthinkers. - Nick Trenton",
  "Daily stack achievements. - John C. Maxwell",
  "The quality of your life depends on the quality of your habits. - James Clear",
  "The successful warrior is the average man, with laser-like focus and disciplined habits. - Bruce Lee",
  "Habits are the silent agreements you make with yourself about how you will live. - Unknown",
  "Select a character trait you admire and identify one small daily habit that would develop that trait. - Unknown",
  "Attract success by becoming. - Jim Rohn",
  "Bad habits are the enemies of your future self. - Anonymous",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Choose most over now. - Abraham Lincoln",
  "A nail is driven out by another nail, habit is overcome by habit. - Desiderius Erasmus",
  "What you repeat in private, you will wear in public. - Unknown",
  "You will never change your life until you change something you do daily. - John C. Maxwell",
  "Table goals habits. - Maxime Lagacé",
  "You become what you repeat. - Jordan Peterson",
  "To change your life, change your priorities; to keep it changed, change your habits. - Unknown",
  "When you have a great and difficult task, something perhaps almost impossible, if you only work a little at a time, every day a little, suddenly the work will finish itself. - Isak Dinesen",
  "Changes that seem small and unimportant at first will compound into remarkable results if you're willing to stick with them for years. - James Clear",
  "You're the sum of your habits. - Chris Donnelly",
  "Small strokes fell great oaks. - Benjamin Franklin",
  "The habit of doing your best, even in small things, prepares you for the big things. - H. Jackson Brown Jr.",
  "The trick to success is to choose the right habit and bring just enough discipline to establish it. - Gary Keller",
  "Your habits are the promises you keep to your future self. - Unknown",
  "I accumulated small but consistent habits that ultimately led to results that were unimaginable when I started. - James Clear",
  "Daily little work finishes the impossible. - Isak Dinesen",
  "Many of us have become habitual overthinkers... - Nick Trenton",
  "Every habit creates a trail; eventually that trail becomes your path. - Unknown",
  "When excellence becomes a habit, then that's just who you are. - Kobe Bryant",
  "The habit of persistence is key to victory. - Herbert Kaufman",
  "A bad habit never disappears miraculously; it is an undo-it-yourself project. - Abigail Van Buren",
  "What you habitually think largely determines what you will ultimately become. - Bruce Lee",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle (via Will Durant)",
  "First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not. - Octavia Butler",
  "Bad habits are like a virus; they spread through your life until you build an immune system of discipline. - Unknown",
  "We are what we repeatedly do. Excellence, then, is not an act but a habit. - Sean Covey",
  "First victory over self. - Harry S. Truman",
  "A daily routine built on good habits and disciplines separates the most successful among us from everyone else. - Darren Hardy",
  "Repetition of the same thought or physical action develops into a habit which, repeated frequently enough, becomes an automatic reflex. - Norman Vincent Peale",
  "It doesn't matter what you do, just do something every day. - Naval Ravikant",
  "Character thoughts habits. - Nick Saban",
  "Do/not power yours. - Aristotle",
  "Winning is not a sometime thing; it's an all-time thing. - Vince Lombardi",
  "Habits are the compound interest of self-improvement. - James Clear",
  "Gotta keep experimenting; success doesn't come from consistency. - Frank Chimero",
  "Habit is either the best of servants or the worst of masters. - Nathaniel Emmons",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "What we hope ever to do with ease, we must first learn to do with diligence. - Samuel Johnson",
  "The habit of managing your mind is the beginning of managing your life. - Robin Sharma",
  "All big things come from small beginnings. The seed of every habit is a single, tiny decision. - James Clear",
  "Repeat become you. - Jordan Peterson",
  "Tread softly; breathe peacefully; laugh hysterically. - Nelson Mandela",
  "Read more books than those who have formal education, make it a lifelong habit. - Robert Greene",
  "What lies in our power to do, it lies in our power not to do. - Aristotle",
  "Little by little, a little becomes a lot. - Tanzanian Proverb",
  "Act sans feeling. - Mel Robbins",
  "Disciplines small daily big. - Unknown",
  "No man is free who is not master of himself. - Epicteto",
  "Sit at a table where they talk about goals, habits, productivity... - Maxime Lagacé",
  "Routines are a godsend when it comes to doing something hard. - Angela Duckworth",
  "Your character isn't fixed – it's shaped by your daily practices. - Ovid",
  "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
  "Al reading the lives of great men, I found that the first victory they won was over themselves. - Harry S. Truman",
  "Leave behind unneeded. - Marie Forleo",
  "Discipline is the habit of doing what you don't want to do when you don't want to do it. - John C. Maxwell",
  "Want most, not now. - Abraham Lincoln",
  "The successful person has the habit of doing the things failures don't like to do. - E. M. Gray",
  "Excellence is an art won by training and habituation. We do not act rightly because we have virtue or excellence, but we rather have those because we have acted rightly. - Aristotle",
  "You leave old habits behind by starting out with the thought, 'I release the need for this in my life.' - Wayne Dyer",
  "Environment makes inevitable. - Unknown",
  "Habits learn life change. - Mel Robbins",
  "Bad habits can cut you down just as easily as good habits can build you up. - James Clear",
  "Routine, in an intelligent man, is a sign of ambition. - W.H. Auden",
  "Clean your room. Organize your life. Get a routine. - Jordan Peterson",
  "A habit missed once is a mistake. Twice is the start of a new habit. - James Clear",
  "Daily something do. - Naval Ravikant",
  "Habit courage choice. - Unknown",
  "Habits, good or bad, are the soul's way of shaping destiny. - Heraclitus",
  "You can judge your future not by your intentions but by your habits. - Andy Andrews",
  "Good habits are the key to all success. Bad habits are the unlocked door to failure. - Og Mandino",
  "Self-discipline is what separates the winners and the losers. - Thomas Peterffy",
  "Habits architects silent. - Colby Kultgen",
  "Exercise first thing in the morning before your brain knows what's doing. - Dan Go",
  "Success is created through the performance of a few small daily disciplines that stack up over time to produce achievements far beyond anything you could have ever planned for. - Unknown",
  "Good habits are formed; bad habits we slip into. - Anonymous",
  "Your habits either weaken your will or strengthen it with every repetition. - Unknown",
  "New habit acquisition challenge. - William James",
  "Daily don't want. - Mark Twain",
  "The chains of habit are too weak to be felt until they are too strong to be broken. - Samuel Johnson",
  "For our purposes, we will define a habit as the intersection of knowledge, skill, and desire. - Stephen R. Covey",
  "All our life, so far as it has definite form, is but a mass of habits. - William James",
  "Environment is the invisible hand that shapes human behavior. - James Clear",
  "Power to do or not. - Aristotle",
  "Make it easy to do what matters and hard to do what doesn't. - James Clear",
  "Gamification turns habits into a game. - Will Moore",
  "Moral excellence comes about as a result of habit. We become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts. - Aristotle",
  "What we do every day matters more than what we do once in a while. - Gretchen Rubin",
  "The chains of habit are generally too small to be felt until they are too heavy to be broken. - Warren Buffett",
  "Great things are not done by impulse, but a series of small things brought together. - Vincent Van Gogh",
  "Sow an act, and you reap a habit; sow a habit, and you reap a character. - Charles Reade",
  "Prevent bad easier than break. - Benjamin Franklin",
  "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time. - John C. Maxwell",
  "Habits are to the soul what joints are to the body. - Blaise Pascal",
  "Excellence through repeated right acts. - Aristotle",
  "Every habit and capability is confirmed and grows in its corresponding actions. - Aristotle",
  "Be the designer of your world and not merely the consumer of it. - James Clear",
  "Form a habit of turning small opportunities into consistent actions. - Les Brown",
  "A nail is driven out by another nail; habit is overcome by habit. - Thomas à Kempis",
  "Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character; sow a character, reap a destiny. - Ralph Waldo Emerson",
  "Experiment for success. - Unknown",
  "Good habits once established are just as hard to break as bad habits. - Edgar Rice Burroughs",
  "By perseverance the snail reached the ark. - Charles Spurgeon",
  "In theory, consistency is about being disciplined, determined, and unwavering. In practice, consistency is about being adaptable. - James Clear",
  "Daily practices shape character. - Ovid",
  "Your future is hidden in your daily schedule. - Mike Murdock",
  "Intensity loses to consistency. - Bruce Lee",
  "Success is the product of daily habits—not once-in-a-lifetime transformations. - James Clear",
  "Routine, in itself, is neither good nor bad; it is the habits inside the routine that make the difference. - Unknown",
  "Your habits will determine your future. - Jack Canfield",
  "Habits are easier to build when they fit into the flow of your life. - James Clear",
  "Quite literally, you become your habits. - James Clear",
  "Verb habit is. - James Clear",
  "Within a year, you will wish you had started today. - Karen Lamb",
  "Ideal life pre-decide. - Dan Koe",
  "The task of breaking a bad habit is like uprooting a powerful oak within us. And the task of building a good habit is like cultivating a delicate flower one day at a time. - James Clear",
  "Slaves to moods without discipline. - Stephen R. Covey",
  "Greatness comes from consistent actions repeated over time, not occasional heroic efforts. - Aristotle",
  "What you do daily determines what you become permanently. - Unknown",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "Systems over excitement. - Jim Ryun",
  "Make good habits and they will make you. - Joyce Meyer",
  "Every workout is a step forward. - Unknown",
  "Discipline turns goals into habits and habits into lifestyles. - Unknown",
  "Drop by drop, habits carve the character like water carves stone. - Unknown",
  "Get rid of the habit of being distracted. - John D. Rockefeller",
  "Chains too weak then too strong. - Samuel Johnson",
  "Future shape habits. - James Clear",
  "Perfection no, consistency yes. - BJ Fogg",
  "Tough habit exit. - Denis Waitley",
  "Sit at a table where they talk about goals, habits, productivity. - Maxime Lagacé",
  "Winning is a habit. Unfortunately, so is losing. - Vince Lombardi",
  "Build the habits that shape your future, not the ones that entertain your present. - James Clear",
  "Every grown-up man consists wholly of habits, although he is often unaware of it and even denies having any habits at all. - Georges Gurdjieff",
  "The habit of persistence is the habit of victory. - Herbert Kaufman",
  "First we form habits, then they form us. - Rob Gilbert",
  "Habits are safer than rules; you don't have to watch them. And you don't have to keep them either. They keep you. - Frank Crane",
  "Excellence is an art won by training and habituation. - Aristotle",
  "A goal is just an outcome—what really drives change is the small habits repeated consistently over time. - Holly M. R. Dickinson",
  "Long-term consistency trumps short-term intensity. - Bruce Lee",
  "The only way you are going to have success is to have lots of failures first. That's where you learn the habits that lead to success. - Dan Peña",
  "Small changes often appear to make no difference until you cross a critical threshold. - James Clear",
  "Self-respect is the fruit of disciplined habits. - Abraham Joshua Heschel",
  "Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. - James Clear",
  "People do not decide their futures, they decide their habits and their habits decide their futures. - F. Matthias Alexander",
  "One of the best ways to build a new habit is to stack it on an existing one. - James Clear",
  "Habits are normal; only the context changes. - Margaret Mead",
  "The acquisition of a new habit, or the leaving off of an old one, we place the difficulty too high. - William James",
  "We build our habits and our habits build us—brick by brick, day by day. - Unknown",
  "The habit of doing more than is necessary can only be earned through practice. - Seth Godin",
  "Adaptable consistency wins. - James Clear",
  "Nothing is stronger than habit. - Ovid",
  "Fast, lift, sprint... Make these habits. Say no to everything else. - Naval Ravikant",
  "Quit talking, begin. - Walt Disney",
  "Too often, we convince ourselves that massive success requires massive action. - James Clear",
  "Perseverance over strength. - Samuel Johnson",
  "The best way to break a bad habit is to drop it. - Leo Aikman",
  "Initial excitement fades; systems keep you consistent. - Jim Ryun",
  "Habits are like comfortable beds. They are easy to get into, but difficult to get out of. - Denis Waitley",
  "The journey of a thousand miles begins with a single step. - Lao Tzu",
  "You do not rise to the level of your goals. You fall to the level of your systems. - James Clear",
  "Repetition is the mother of skill and the architect of habit. - Tony Robbins",
  "Peaceful persistence. - Nelson Mandela",
  "Habits are the invisible script that directs your visible performance. - Unknown",
  "All habits gather by unseen degrees. - John Dryden",
  "True freedom is impossible without a mind made free by discipline. - Mortimer J. Adler",
  "Train to win the art of excellence. - Aristotle",
  "Nothing changes if your habits don't. - Joyce Meyer",
  "Mind free by discipline. - Mortimer J. Adler",
  "Good habits save you from having to be constantly heroic. - David T. Bentley",
  "Discipline or regret pain. - Jim Rohn",
  "Improvement compounds. - James Clear",
  "We become what we repeatedly do. - Aristotle",
  "Trait via daily habit. - Unknown",
  "Good habits formed at youth make all the difference. - Aristotle",
  "Good habits result from resisting temptation. - Ancient Proverb",
  "A man who can't bear to share his habits is a man who needs to quit them. - Stephen King",
  "Keep the faculty of effort alive in you by a little gratuitous exercise every day. - William James",
  "You'll never change your life until you change something you do daily. - Mike Murdock",
  "It is so easy to overestimate the importance of one defining moment and underestimate the value of making small improvements on a daily basis. - James Clear",
  "You get what you repeat. - James Clear",
  "Nothing happens until something moves. Make movement a habit. - Albert Einstein",
  "The fixity of a habit is generally in proportion to its absurdity. - Marcel Proust",
  "Bad habits are like a comfortable bed, easy to get into, but hard to get out of. - Unknown",
  "Ritual is routine infused with mindfulness. - Kent Nerburn",
  "Victory persistence habit. - Herbert Kaufman",
  "One little step taken every day adds up to big results over time. Make that step a habit. - Karen Salmansohn",
  "The first and greatest victory is to conquer yourself. - Plato",
  "Change might not be fast and it isn't always easy. But with time and habit, almost any change is possible. - Charles Duhigg",
  "Let's make it a game to eliminate your pain. - Will Moore",
  "Automatic via repetition. - Norman Vincent Peale",
  "Energy and persistence conquer all things. - Benjamin Franklin",
  "Daily flower or oak. - James Clear",
  "What lies in our power to do, lies in our power not to do. - Aristotle",
  "Your habits are often a byproduct of convenience. - James Clear",
  "Direction, not intention, is determined by your habits. - Andy Stanley",
  "Consistent micro-habits for excellence. - Unknown",
  "Form habits, they form you. - John Dryden",
  "First we make our habits, then our habits make us. - John Dryden",
];

/**
 * Get the citation for today based on the day of the year.
 * Uses citations sequentially by day number (day 1 = citation[0], day 2 = citation[1], etc.)
 * For leap years (366 days), uses citation[365]. For non-leap years (365 days), uses citation[364] on day 365.
 * @returns The citation string for today
 */
export function getDailyCitation(): string {
  const now = new Date();
  const startOfYear = new Date(now.getFullYear(), 0, 1);
  const dayOfYear =
    Math.floor(
      (now.getTime() - startOfYear.getTime()) / (1000 * 60 * 60 * 24)
    ) + 1;

  // If no citations provided, return a default message
  if (citations.length === 0) {
    return "Welcome to Habitus - Your daily habit tracker";
  }

  // Use citation by day number (day 1 = index 0, day 2 = index 1, etc.)
  // For non-leap years, day 365 uses citation[364]. For leap years, day 366 uses citation[365].
  const citationIndex = Math.min(dayOfYear - 1, citations.length - 1);
  return citations[citationIndex];
}
